"""Add Parameter table and link to SensorData

Revision ID: 239fc8c71ef5
Revises: 577a6a74a9db
Create Date: 2025-04-18 15:55:15.040161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '239fc8c71ef5'
down_revision: Union[str, None] = '577a6a74a9db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parameters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('sensor_data', sa.Column('parameter_id', sa.Integer(), nullable=False))
    op.add_column('sensor_data', sa.Column('time', sa.DateTime(timezone=True), nullable=False))
    op.drop_constraint('sensor_data_device_id_key', 'sensor_data', type_='unique')
    op.create_foreign_key(None, 'sensor_data', 'parameters', ['parameter_id'], ['id'])
    op.drop_column('sensor_data', 'device_id')
    op.drop_column('sensor_data', 'metric')
    op.drop_column('sensor_data', 'timestamp')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensor_data', sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('sensor_data', sa.Column('metric', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('sensor_data', sa.Column('device_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'sensor_data', type_='foreignkey')
    op.create_unique_constraint('sensor_data_device_id_key', 'sensor_data', ['device_id'])
    op.drop_column('sensor_data', 'time')
    op.drop_column('sensor_data', 'parameter_id')
    op.drop_table('parameters')
    # ### end Alembic commands ###
